name: Docker Image CI

on:
  push:
    branches: [ "**", "**/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd docker && pwd && ls -a && docker build . --tag test-build:$(date +%s)