name: Docker Image CI

on:
  push:
    branches: [ "**/**", "**"]
  pull_request:
    branches: [ "master", "**deploy/**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./docker --file Dockerfile --tag test-image:$(date +%s)
